import * as mongoose from 'mongoose';

const Schema = mongoose.Schema;
export const User = new Schema({
  recentSearch: Array(String),
  firstName: { type: String, index: true },
  lastName: { type: String, index: true },
  email: String,
  password: String,
  country: String,
  birthDate: Date,
  followingTopics: Array(mongoose.Types.ObjectId),
  location: String,
  activateaccount: Boolean,
  notificationCounter: Number,
  activity: Boolean,
  lastTopics: Array({
    topicName: String,
    pinsLength: Number,
  }),
  invitation: Boolean,
  boardUpdate: Boolean,
  followNotification: Boolean,
  pinsNotification: Boolean,
  facebook: Boolean,
  google: Boolean,
  notificationOfPinsActivity: Boolean,
  userName: { type: String, index: true },
  boardsForYou: Boolean,
  pinsForYou: Boolean,
  pinsInspired: Boolean,
  popularPins: Boolean,
  about: String,
  sortType: String,
  gender: String,
  socketId: String,
  homeFeed: Array(Object),
  history: Array({
    topic: String,
    pinId: mongoose.Types.ObjectId,
  }),
  googleImage: String,
  profileImage: String,
  pins: Array({
    pinId: mongoose.Types.ObjectId,
    boardId: mongoose.Types.ObjectId,
    sectionId: mongoose.Types.ObjectId,
  }),
  savedPins: Array({
    pinId: mongoose.Types.ObjectId,
    boardId: mongoose.Types.ObjectId,
    sectionId: mongoose.Types.ObjectId,
    note: String,
  }),
  confirm: Boolean,
  fcmToken: String,
  notifications: [{}],
  offlineNotifications: [{}],
  followers: Array(mongoose.Types.ObjectId),
  following: Array(mongoose.Types.ObjectId),
  viewState: String,
  boards: [
    {
      boardId: mongoose.Types.ObjectId,
      name: String,
      createdAt: Date,
      isJoined: Boolean,
      createdOrjoined: String,
    },
  ],
  counts: {
    likes: Number,
    comments: Number,
    repins: Number,
    saves: Number,
  },
  createdAt: Date,
});
